on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Project
        uses: actions/setup-node@v3
        with:
          always-auth: true
      - run: |
          echo "//npm.greensock.com/:_authToken=${{ secrets.GSAP_TOKEN }}" >> ~/.npmrc
          echo "@gsap:registry=https://npm.greensock.com" >> ~/.npmrc
      - run: yarn
      - run: yarn build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hamsa
          directory: dist
